2023-07-03 07:22:03,867 | INFO | [-] Stating Application
2023-07-03 07:22:04,321 | INFO | Pika version 1.3.1 connecting to ('10.12.1.151', 5672)
2023-07-03 07:22:07,405 | ERROR | Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 36822)>; error=113 (No route to host)
2023-07-03 07:22:07,406 | ERROR | TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.12.1.151', 5672))
2023-07-03 07:22:07,413 | ERROR | AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2023-07-03 07:22:07,420 | ERROR | AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2023-07-03 07:22:07,426 | ERROR | AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:22:07,427 | ERROR | Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:22:07,428 | ERROR | Error in _create_connection().
Traceback (most recent call last):
  File "/home/pi/Documents/Sudisa/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2023-07-03 07:22:47,493 | INFO | Pika version 1.3.1 connecting to ('10.12.1.151', 5672)
2023-07-03 07:22:50,605 | ERROR | Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 36826)>; error=113 (No route to host)
2023-07-03 07:22:50,606 | ERROR | TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.12.1.151', 5672))
2023-07-03 07:22:50,607 | ERROR | AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2023-07-03 07:22:50,608 | ERROR | AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2023-07-03 07:22:50,609 | ERROR | AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:22:50,610 | ERROR | Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:22:50,611 | ERROR | Error in _create_connection().
Traceback (most recent call last):
  File "/home/pi/Documents/Sudisa/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2023-07-03 07:23:30,663 | INFO | Pika version 1.3.1 connecting to ('10.12.1.151', 5672)
2023-07-03 07:23:33,805 | ERROR | Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 36830)>; error=113 (No route to host)
2023-07-03 07:23:33,806 | ERROR | TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.12.1.151', 5672))
2023-07-03 07:23:33,807 | ERROR | AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2023-07-03 07:23:33,808 | ERROR | AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2023-07-03 07:23:33,809 | ERROR | AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:23:33,810 | ERROR | Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2023-07-03 07:23:33,811 | ERROR | Error in _create_connection().
Traceback (most recent call last):
  File "/home/pi/Documents/Sudisa/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2023-07-04 01:05:57,344 | INFO | [-] Stating Application
2023-07-04 01:05:57,622 | INFO | Pika version 1.3.1 connecting to ('10.12.1.131', 5672)
2023-07-04 01:05:57,624 | INFO | Socket connected: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,631 | INFO | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756af2b0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756af2b0> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>).
2023-07-04 01:05:57,635 | ERROR | Socket EOF; <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,636 | ERROR | Transport indicated EOF.
2023-07-04 01:05:57,636 | INFO | protocol.eof_received() elected to close: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,637 | INFO | _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,637 | INFO | Deactivating transport: state=1; <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,638 | ERROR | connection_lost: StreamLostError: ('Transport indicated EOF',)
2023-07-04 01:05:57,642 | INFO | AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2023-07-04 01:05:57,644 | ERROR | Probably incompatible Protocol Versions
2023-07-04 01:05:57,645 | INFO | Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2023-07-04 01:05:57,648 | ERROR | AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2023-07-04 01:05:57,651 | ERROR | AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None.
2023-07-04 01:05:57,654 | ERROR | AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2023-07-04 01:05:57,655 | INFO | Closing transport socket and unlinking: state=3; <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54988), raddr=('10.12.1.131', 5672)>
2023-07-04 01:05:57,655 | ERROR | Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2023-07-04 01:05:57,656 | ERROR | Error in _create_connection().
Traceback (most recent call last):
  File "/home/pi/Documents/Sudisa/env/lib/python3.5/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2023-07-04 01:06:37,710 | INFO | Pika version 1.3.1 connecting to ('10.12.1.131', 5672)
2023-07-04 01:06:37,714 | INFO | Socket connected: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 54996), raddr=('10.12.1.131', 5672)>
2023-07-04 01:06:37,720 | INFO | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756afa10>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756afa10> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>).
2023-07-04 01:06:37,757 | INFO | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756afa10> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:06:37,763 | INFO | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756afa10> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:06:37,764 | INFO | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x756afa10> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:06:37,768 | INFO | Created channel=1
2023-07-04 01:07:16,987 | INFO | [-] Stating Application
2023-07-04 01:07:17,270 | INFO | Pika version 1.3.1 connecting to ('10.12.1.131', 5672)
2023-07-04 01:07:17,273 | INFO | Socket connected: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.12.1.53', 55004), raddr=('10.12.1.131', 5672)>
2023-07-04 01:07:17,279 | INFO | Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75657290>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75657290> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>).
2023-07-04 01:07:17,322 | INFO | AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75657290> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:07:17,325 | INFO | AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75657290> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:07:17,326 | INFO | Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x75657290> params=<ConnectionParameters host=10.12.1.131 port=5672 virtual_host=/ ssl=False>>
2023-07-04 01:07:17,328 | INFO | Created channel=1
